name: nucleicnet
channels:
- defaults
dependencies:
- backports=1.0=py27_0
- decorator=4.1.2=py27_0
- enum34=1.1.6=py27_0
- get_terminal_size=1.0.0=py27_0
- ipython=5.3.0=py27_0
- ipython_genutils=0.2.0=py27_0
- openssl=1.0.2l=0
- path.py=10.3.1=py27_0
- pathlib2=2.3.0=py27_0
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pip=9.0.1=py27_1
- prompt_toolkit=1.0.15=py27_0
- ptyprocess=0.5.2=py27_0
- pygments=2.2.0=py27_0
- python=2.7.13=0
- readline=6.2=2
- scandir=1.5=py27_0
- setuptools=27.2.0=py27_0
- simplegeneric=0.8.1=py27_1
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- traitlets=4.3.2=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.11=0
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - backports.weakref==1.0rc1
  - biopandas==0.2.2
  - bleach==1.5.0
  - certifi==2017.1.23
  - configparser==3.5.0
  - cycler==0.10.0
  - easydict==1.7
  - entrypoints==0.2.2
  - funcsigs==1.0.2
  - functools32==3.2.3.post2
  - h5py==2.7.1
  - html5lib==0.9999999
  - imgaug==0.2.5
  - ipykernel==4.6.1
  - ipython-genutils==0.2.0
  - ipywidgets==5.2.2
  - jinja2==2.9.5
  - jsonschema==2.6.0
  - jupyter==1.0.0
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - keras==2.2.0
  - keras-applications==1.0.2
  - keras-preprocessing==1.0.1
  - markdown==2.6.9
  - markupsafe==0.23
  - matplotlib==2.0.0
  - mistune==0.7.3
  - mock==2.0.0
  - mpmath==0.19
  - msgpack-python==0.4.8
  - nbconvert==5.1.1
  - nbformat==4.2.0
  - networkx==2.0
  - notebook==5.2.0
  - numpy==1.13.1
  - olefile==0.44
  - opencv-python==3.4.0.12
  - pandas==0.22.0
  - seaborn==0.9.0
  - pandocfilters==1.4.1
  - pbr==3.1.1
  - pillow==4.2.1
  - prompt-toolkit==1.0.15
  - protobuf==3.4.0
  - pyparsing==2.2.0
  - python-dateutil==2.6.1
  - pytz==2017.2
  - pywavelets==0.5.2
  - pyyaml==3.12
  - pyzmq==16.0.2
  - qtconsole==4.2.1
  - scikit-image==0.13.1
  - scikit-learn==0.19.0
  - scipy==1.0.1
  - singledispatch==3.4.0.3
  - sklearn==0.0
  - subprocess32==3.2.7
  - sympy==1.0
  - tensorflow-gpu==1.2.1
  - tensorlayer==1.6.5
  - terminado==0.6
  - testpath==0.3
  - tflearn==0.3.2
  - tornado==4.4.2
  - tqdm==4.19.4
  - ujson==1.35
  - werkzeug==0.12.2
  - widgetsnbextension==1.2.6
  - xlrd==1.1.0
